### ISSUE TITLE
CAPI support not working from latest(0.65) Putty

### ISSUE THREAD

**Issue by jbjonesjr** [risacher/putty-cac#18] opened 2015-08-24 17:48 UTC
this is really a @jdantzler problem, but affects www.risacher.org since it is currently hosting it.

**Problem:** Using CAPI authentication from latest Putty doesn't attempt to send key (tested with all three flavors, downloaded Aug 22 or later from risacher.org/putty-cac).  Adding it into pagent works. This worked in the 0.62 version.

#### Reproduce:
* Ensure no cert available in Pagent
* Launch putty.exe
  * Session:
    * Host: github.com
    * Close on exit: NEVER
  * Connection/SSH/CAPI
    * Attempt "CAPI Certificate" (key-only) auth (SSH2) : YES
    * Cert: `Browse` -> select cert
* `Open`
* Use **git** when prompted for a username
* Response:  

> Disconnected: No supported authentication methods available (server sent: publicKey)

#### Success:
* Launch pagent.exe
* Add CAPI cert to pagegnt via right click pagent in systray -> `View Keys` -> `Add CAPI Cert` -> select cert. Close pagent
* Launch putty.exe
  * Session:
    * Host: github.com
    * Close on exit: NEVER
* `Open`
* Use **git** when prompted for a username
* Response:  

> Authentication with public key "CAPI:User\MY\ \<hex\>" from agent
Server refused to allocate pty
Hi jbjonesjr! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by jbjonesjr** [comment] 2015-08-24 17:49
As should be apparent, i've added my Smart Card ssh key into my github account.  The "Success" section confirms that this was done correctly.

**Comment by jdantzler** [comment] 2015-08-25 18:44
I can reproduce this issue as well when using putty instead of pageant for authentication.  For now continue to use pageant until this is fixed.  I will look and see if I can find and fix the issue when I get a chance.  Thanks for reporting this.

**Comment by jbjonesjr** [comment] 2015-08-25 19:12
Happy to help.

**Comment by risacher** [comment] 2015-09-30 14:10
@jbjonesjr Can you retest with the current executables in https://risacher.org/putty-cac/testing/Release/ or in the /executables folder in my repo?  I thin this is fixed.

**Comment by jbjonesjr** [comment] 2015-09-30 14:28
@risacher Yes I can. End of FY means I'm currently awaiting an updated CAC card, so may be a few days/weeks (yeh Government!), but will get it as soon as my CAC is back.

**Comment by risacher** [comment] 2015-12-30 13:38
Closing issue.  This is fixed.

**Closed by risacher** 2015-12-30 13:38 UTC

**Comment by jbjonesjr** [comment] 2015-12-30 14:57
sorry for the delay @risacher , i'm currently awaiting a cac renewal.
#contractorLife #CACexpiresAsSoonAsIGetIt

**Comment by risacher** [comment] 2015-12-31 17:59
@jbjonesjr When you get it - test the 0.66-sync branch and let me know how it turns out.
