### ISSUE TITLE
In CITRIX, putty-cac does not reopen certificates

### ISSUE THREAD

**Issue by LinuxSneaker** [risacher/putty-cac#40] opened 2017-04-14 00:19 UTC
I am running Release_0.68_1, which works when I am connected through CITRIX (for which I am very grateful).  However, there is an issue after being connected for a while.  At some point, putty-cac fails to connect to systems, and you get a "CAPI failed to sign data".  A work around is to go to another app (e.g. ActivClient Agent), and do something that requires the user to input the PIN, such as looking at "Personal Data".  After this, putty-cac again works for a while.

Here is the sanitized logs:
2017-04-13 20:03:35	Connecting to X.X.X.X port 22
2017-04-13 20:03:35	We claim version: SSH-2.0-PuTTY_
2017-04-13 20:03:35	Server version: SSH-2.0-OpenSSH_5.3
2017-04-13 20:03:35	We believe remote version has SSH-2 channel request bug
2017-04-13 20:03:35	Using SSH protocol version 2
2017-04-13 20:03:35	Doing Diffie-Hellman group exchange
2017-04-13 20:03:35	Doing Diffie-Hellman key exchange with hash SHA-256
2017-04-13 20:03:35	Server also has ssh-dss host key, but we don't know it
2017-04-13 20:03:35	Host key fingerprint is:
2017-04-13 20:03:35	ssh-rsa 2048 XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX
2017-04-13 20:03:35	Initialised AES-256 SDCTR client->server encryption
2017-04-13 20:03:35	Initialised HMAC-SHA-256 client->server MAC algorithm
2017-04-13 20:03:35	Initialised AES-256 SDCTR server->client encryption
2017-04-13 20:03:35	Initialised HMAC-SHA-256 server->client MAC algorithm
2017-04-13 20:03:35	Use CAPI cert (User\MY\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
2017-04-13 20:03:35	Offered public key
2017-04-13 20:03:35	Offer of public key accepted
2017-04-13 20:03:41	CAPI failed to sign data

**Comment by NoMoreFood** [comment] 2017-04-20 01:24
@LinuxSneaker Before I think about this too hard, can you please confirm the issue still exists in exists in PuTTY CAC 0.68 Update 2 Pre-Release.

**Comment by NoMoreFood** [comment] 2017-05-02 23:38
@LinuxSneaker Any update?

**Comment by LinuxSneaker** [comment] 2017-05-02 23:41
I am trying to get the executable onto the system in question....I should know if the issue is fixed in your latest release this week.  Thank you for keeping track of this!

**Comment by LinuxSneaker** [comment] 2017-05-04 00:50
The problem is worst in the newest release, as I cannot log onto the same system that worked with previous prerelease version.  I even tried copying the ssh key from the new version and pasting it onto the server, but it didn't work.  Repeatedly, 0.68_1 works, 0.69 doesn't.   Here are the two logs:

2017-05-03 20:36:39	Connecting to x.x.x.x port 22
2017-05-03 20:36:39	We claim version: SSH-2.0-PuTTY_Release_0.68_1
2017-05-03 20:36:39	Server version: SSH-2.0-OpenSSH_5.3
2017-05-03 20:36:39	We believe remote version has SSH-2 channel request bug
2017-05-03 20:36:39	Using SSH protocol version 2
2017-05-03 20:36:39	Using Diffie-Hellman with standard group "group14"
2017-05-03 20:36:39	Doing Diffie-Hellman key exchange with hash SHA-1
2017-05-03 20:36:39	Server also has ssh-dss host key, but we don't know it
2017-05-03 20:36:39	Host key fingerprint is:
2017-05-03 20:36:39	ssh-rsa 2048 xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
2017-05-03 20:36:39	Initialised AES-256 SDCTR client->server encryption
2017-05-03 20:36:39	Initialised HMAC-SHA-256 client->server MAC algorithm
2017-05-03 20:36:39	Initialised AES-256 SDCTR server->client encryption
2017-05-03 20:36:39	Initialised HMAC-SHA-256 server->client MAC algorithm
2017-05-03 20:36:39	Use CAPI cert (User\MY\BCXXXXXXXXXXXXXXXXXXXXXXXXXX65)
2017-05-03 20:36:39	Offered public key
2017-05-03 20:36:39	Offer of public key accepted
2017-05-03 20:36:45	Sent public key signature
2017-05-03 20:36:45	Access granted
2017-05-03 20:36:45	Opening session as main channel
2017-05-03 20:36:45	Opened main channel
2017-05-03 20:36:45	Allocated pty (ospeed 38400bps, ispeed 38400bps)
2017-05-03 20:36:45	Started a shell/command


2017-05-03 20:37:43	Connecting to 10.1.1.162 port 22
2017-05-03 20:37:43	We claim version: SSH-2.0-PuTTY_Release_0.69
2017-05-03 20:37:43	Server version: SSH-2.0-OpenSSH_5.3
2017-05-03 20:37:43	We believe remote version has SSH-2 channel request bug
2017-05-03 20:37:43	Using SSH protocol version 2
2017-05-03 20:37:43	Using Diffie-Hellman with standard group "group14"
2017-05-03 20:37:43	Doing Diffie-Hellman key exchange with hash SHA-1
2017-05-03 20:37:43	Server also has ssh-dss host key, but we don't know it
2017-05-03 20:37:43	Host key fingerprint is:
2017-05-03 20:37:43	ssh-rsa 2048 xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
2017-05-03 20:37:43	Initialised AES-256 SDCTR client->server encryption
2017-05-03 20:37:43	Initialised HMAC-SHA-256 client->server MAC algorithm
2017-05-03 20:37:43	Initialised AES-256 SDCTR server->client encryption
2017-05-03 20:37:43	Initialised HMAC-SHA-256 server->client MAC algorithm
2017-05-03 20:37:43	Reading key file "CAPI:bcXXXXXXXXXXXXXXXXXXXXXXXXXX65"
2017-05-03 20:37:43	Offered public key
2017-05-03 20:37:43	Offer of public key accepted
2017-05-03 20:37:44	Sent public key signature
2017-05-03 20:37:44	Server refused public-key signature despite accepting key!
2017-05-03 20:37:44	Using SSPI from SECUR32.DLL
2017-05-03 20:37:44	Attempting GSSAPI authentication
2017-05-03 20:37:44	GSSAPI authentication initialisation failed
2017-05-03 20:37:44	The target was not recognized.

**Comment by NoMoreFood** [comment] 2017-05-04 10:17
@LinuxSneaker Alright, thanks for testing.  I'll try to figure out what's going on with this -- looks like the new version isn't signing properly.  Does the PIN prompt to come up?

**Comment by NoMoreFood** [comment] 2017-05-04 10:41
@LinuxSneaker Also, what OS are you running on the client?

**Comment by LinuxSneaker** [comment] 2017-05-04 12:07
No, I am not prompted for a PIN.  The client at the end of the Citrix session is Windows 7 Enterprise, and I am trying to connect to RHEL6 with putty-cac.

**Comment by NoMoreFood** [comment] 2017-05-04 15:52
@LinuxSneaker   Alright, thanks for the information.  That helps isolate where in the code the problem is occurring.  I'll post a version with additional logging enabled by tomorrow to help us track this down.

**Comment by NoMoreFood** [comment] 2017-05-05 04:22
@LinuxSneaker If you could give the attached version a try and let me know if you get an additional popup error message when connecting, I'd appreciate it.

[puttycac-0.69-debug.zip](https://github.com/risacher/putty-cac/files/978098/puttycac-0.69-debug.zip)

**Comment by LinuxSneaker** [comment] 2017-05-19 14:07
Verified ssh key on server, and made sure the certificate was loaded.  Here is the log:
2017-05-19 09:57:32	Connecting to 10.1.1.162 port 22
2017-05-19 09:57:32	We claim version: SSH-2.0-PuTTY_Release_0.69
2017-05-19 09:57:32	Server version: SSH-2.0-OpenSSH_5.3
2017-05-19 09:57:32	We believe remote version has SSH-2 channel request bug
2017-05-19 09:57:32	Using SSH protocol version 2
2017-05-19 09:57:32	Using Diffie-Hellman with standard group "group14"
2017-05-19 09:57:32	Doing Diffie-Hellman key exchange with hash SHA-1
2017-05-19 09:57:32	Server also has ssh-dss host key, but we don't know it
2017-05-19 09:57:32	Host key fingerprint is:
2017-05-19 09:57:32	ssh-rsa 2048 xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
2017-05-19 09:57:32	Initialised AES-256 SDCTR client->server encryption
2017-05-19 09:57:32	Initialised HMAC-SHA-256 client->server MAC algorithm
2017-05-19 09:57:32	Initialised AES-256 SDCTR server->client encryption
2017-05-19 09:57:32	Initialised HMAC-SHA-256 server->client MAC algorithm
2017-05-19 09:57:32	Reading key file "CAPI:bcXXXXXXXXXXXXXXXXXXXXXXXXXX65"
2017-05-19 09:57:32	Offered public key
2017-05-19 09:57:32	Offer of public key accepted
2017-05-19 09:57:39	Sent public key signature
2017-05-19 09:57:39	Server refused public-key signature despite accepting key!
2017-05-19 09:57:39	Using SSPI from SECUR32.DLL
2017-05-19 09:57:39	Attempting GSSAPI authentication
2017-05-19 09:57:44	GSSAPI authentication initialisation failed
2017-05-19 09:57:44	The target was not recognized.

A window popped up during this which said:
Could not certificate acquire private key context: -2146893792

**Comment by NoMoreFood** [comment] 2018-01-20 01:54
@LinuxSneaker  Is this still an issue or can I close this?

**Comment by NoMoreFood** [comment] 2018-07-28 13:36
Closing due to lack of response.

**Closed by NoMoreFood** 2018-07-28 13:36 UTC
